# Generated by Django 6.0.3 on 2026-03-13 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-created_at'], 'verbose_name': 'Promo Campaign', 'verbose_name_plural': 'Promo Campaigns'},
        ),
        migrations.AlterModelOptions(
            name='referral',
            options={'verbose_name': 'Referral', 'verbose_name_plural': 'Referrals'},
        ),
        migrations.AlterModelOptions(
            name='rewardclaim',
            options={'verbose_name': 'Reward Claim', 'verbose_name_plural': 'Reward Claims'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['order'], 'verbose_name': 'Campaign Task', 'verbose_name_plural': 'Campaign Tasks'},
        ),
        migrations.AlterModelOptions(
            name='usertask',
            options={'verbose_name': 'Task Submission', 'verbose_name_plural': 'Task Submissions'},
        ),
    ]
