# Generated by Django 4.2.7 on 2026-03-11 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonyComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Share your testimony or experience')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimony_comments/photos/')),
                ('video', models.FileField(blank=True, null=True, upload_to='testimony_comments/videos/')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('device_received', models.CharField(blank=True, help_text='Which Samsung device did you receive?', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_testimonies', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimony_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Testimony Comment',
                'verbose_name_plural': 'Testimony Comments',
                'ordering': ['-created_at'],
            },
        ),
    ]
