# Generated by Django 6.0.3 on 2026-03-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_testimonycomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Newsletter Subscriber',
                'verbose_name_plural': 'Newsletter Subscribers',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Announcement', 'verbose_name_plural': 'Announcements'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['-created_at'], 'verbose_name': 'Samsung Device', 'verbose_name_plural': 'Samsung Devices'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-created_at'], 'verbose_name': 'Customer Story', 'verbose_name_plural': 'Customer Stories'},
        ),
        migrations.AlterModelOptions(
            name='testimonycomment',
            options={'ordering': ['-created_at'], 'verbose_name': 'User Testimony', 'verbose_name_plural': 'User Testimonies'},
        ),
    ]
