# Generated by Django 6.0.3 on 2026-03-13 00:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promotions', '0002_alter_campaign_options_alter_referral_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(blank=True, editable=False, help_text='Auto-generated unique certificate number', max_length=30, unique=True)),
                ('verification_hash', models.CharField(blank=True, editable=False, help_text='SHA-256 hash for certificate verification', max_length=64, unique=True)),
                ('recipient_name', models.CharField(help_text='Full name as it appears on the certificate', max_length=200)),
                ('recipient_location', models.CharField(blank=True, help_text='Country or location of the recipient', max_length=200)),
                ('recipient_country_code', models.CharField(blank=True, default='US', help_text='ISO country code for flag display (e.g. US, BB, NG, GH, KE)', max_length=5)),
                ('certificate_type', models.CharField(choices=[('lottery_award', 'Samsung Lottery Award'), ('promo_winner', 'Online Promo Winner'), ('ambassador', 'Ambassador Recognition'), ('referral_champion', 'Referral Champion'), ('task_completion', 'Task Completion Award')], default='promo_winner', max_length=20)),
                ('award_amount', models.DecimalField(decimal_places=2, default=0, help_text='The dollar amount awarded', max_digits=12)),
                ('award_description', models.TextField(blank=True, help_text='Custom description text for the certificate body')),
                ('issuer_name', models.CharField(default='Samsung Promo Portal', help_text='Name of the issuing authority', max_length=200)),
                ('issuer_title', models.CharField(default='Senior Online Manager', help_text='Title of the issuing authority', max_length=200)),
                ('authorized_signatory', models.CharField(default='Steven Smith', help_text='Name of the person who signs the certificate', max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('revoked', 'Revoked')], default='issued', max_length=10)),
                ('issued_date', models.DateField(default=django.utils.timezone.now, help_text='Date printed on the certificate')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, help_text='The campaign this certificate is related to (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='promotions.campaign')),
                ('user', models.ForeignKey(help_text='The user this certificate is issued to', on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Winner Certificate',
                'verbose_name_plural': 'Winner Certificates',
                'ordering': ['-created_at'],
            },
        ),
    ]
