# Generated by Django 6.0.3 on 2026-03-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='recipient_country_code',
            field=models.CharField(choices=[('US', '🇺🇸 United States'), ('GB', '🇬🇧 United Kingdom'), ('CA', '🇨🇦 Canada'), ('AU', '🇦🇺 Australia'), ('NG', '🇳🇬 Nigeria'), ('GH', '🇬🇭 Ghana'), ('KE', '🇰🇪 Kenya'), ('ZA', '🇿🇦 South Africa'), ('TZ', '🇹🇿 Tanzania'), ('UG', '🇺🇬 Uganda'), ('CM', '🇨🇲 Cameroon'), ('SN', '🇸🇳 Senegal'), ('CI', '🇨🇮 Ivory Coast'), ('ET', '🇪🇹 Ethiopia'), ('RW', '🇷🇼 Rwanda'), ('BB', '🇧🇧 Barbados'), ('JM', '🇯🇲 Jamaica'), ('TT', '🇹🇹 Trinidad & Tobago'), ('IN', '🇮🇳 India'), ('PK', '🇵🇰 Pakistan'), ('BD', '🇧🇩 Bangladesh'), ('PH', '🇵🇭 Philippines'), ('MY', '🇲🇾 Malaysia'), ('SG', '🇸🇬 Singapore'), ('ID', '🇮🇩 Indonesia'), ('AE', '🇦🇪 UAE'), ('SA', '🇸🇦 Saudi Arabia'), ('DE', '🇩🇪 Germany'), ('FR', '🇫🇷 France'), ('IT', '🇮🇹 Italy'), ('ES', '🇪🇸 Spain'), ('NL', '🇳🇱 Netherlands'), ('BR', '🇧🇷 Brazil'), ('MX', '🇲🇽 Mexico'), ('CO', '🇨🇴 Colombia'), ('AR', '🇦🇷 Argentina'), ('KR', '🇰🇷 South Korea'), ('JP', '🇯🇵 Japan'), ('CN', '🇨🇳 China'), ('EG', '🇪🇬 Egypt'), ('MA', '🇲🇦 Morocco'), ('IE', '🇮🇪 Ireland'), ('SE', '🇸🇪 Sweden'), ('NO', '🇳🇴 Norway'), ('NZ', '🇳🇿 New Zealand'), ('TR', '🇹🇷 Turkey'), ('PL', '🇵🇱 Poland')], default='US', help_text='Select the country — its flag will appear on the certificate', max_length=5, verbose_name='Recipient Flag / Country'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='recipient_location',
            field=models.CharField(blank=True, help_text='Country or city of the recipient', max_length=200),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='recipient_name',
            field=models.CharField(blank=True, help_text='Full name as printed on the certificate (leave blank to auto-fill from user)', max_length=200),
        ),
    ]
